from collections.abc import Callable

from fastapi import APIRouter, HTTPException, Request

from ...config import Settings
from ...files import discover_session_files, read_session_messages, resolve_chat_file
from ...pi_rpc import PiRpcError, PiRuntimeManager
from ...store import Store


def create_router(
    settings: Settings,
    store: Store,
    runtime: PiRuntimeManager,
    visible_or_404: Callable[[dict | None, Request, str], dict],
    has_session_file: Callable[[dict], bool],
    visible_messages: Callable[[list[dict], str], list[dict]],
) -> APIRouter:
    router = APIRouter(prefix="/api", tags=["shares"])

    @router.post("/chats/{chat_id}/share")
    async def create_chat_share(chat_id: str, request: Request):
        chat = visible_or_404(store.get_chat(chat_id), request, "Chat")
        share = store.create_share(chat_id, user_id=chat.get("user_id"))
        return {"token": share["token"], "url": f"/share/{share['token']}"}

    @router.get("/share/{token}")
    async def get_shared_chat(token: str):
        share = store.get_share(token)
        if not share:
            raise HTTPException(404, "Share not found")
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        if chat["status"] != "created" and has_session_file(chat):
            try:
                messages = await runtime.messages(chat)
            except PiRpcError as exc:
                raise HTTPException(503, str(exc)) from exc
        else:
            messages = []
        return {
            "chat": {
                "title": chat.get("title"),
                "created_at": chat.get("created_at"),
                "updated_at": chat.get("updated_at"),
                "agent_id": chat.get("agent_id"),
            },
            "messages": visible_messages(messages, "production"),
        }

    @router.get("/share/{token}/files")
    async def list_shared_chat_files(token: str):
        share = store.get_share(token)
        if not share:
            raise HTTPException(404, "Share not found")
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        session_file = runtime.newest_session_file(chat)
        files = (
            discover_session_files(session_file, settings.pi_cwd)
            if session_file
            else []
        )
        return {"files": files}

    @router.get("/share/{token}/files/content")
    async def get_shared_chat_file(token: str, path: str):
        share = store.get_share(token)
        if not share:
            raise HTTPException(404, "Share not found")
        chat = store.get_chat(share["chat_id"])
        if not chat:
            raise HTTPException(404, "Share not found")
        session_file = runtime.newest_session_file(chat)
        messages = read_session_messages(session_file) if session_file else []
        file_path = resolve_chat_file(messages, settings.pi_cwd, path)
        if not file_path:
            raise HTTPException(404, "File not found or not generated by this chat")
        try:
            content = file_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            raise HTTPException(415, "File is not a readable UTF-8 text file") from exc
        return {"content": content}

    return router
